apiVersion: v1
kind: Service
metadata:
  name: ${CI_PROJECT_NAME}-service
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: ${CI_PROJECT_NAME}
    environment: ${KUBE_NAMESPACE}
spec:
  selector:
    app: ${CI_PROJECT_NAME}
    environment: ${KUBE_NAMESPACE}
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${CI_PROJECT_NAME}-ingress
  namespace: ${KUBE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - ${CI_PROJECT_NAME}-${KUBE_NAMESPACE}.yourdomain.com
    secretName: ${CI_PROJECT_NAME}-${KUBE_NAMESPACE}-tls
  rules:
  - host: ${CI_PROJECT_NAME}-${KUBE_NAMESPACE}.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${CI_PROJECT_NAME}-service
            port:
              number: 80